import type { Metadata } from "next";
import { Geist, Geist_Mono ,Exo} from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import Header from "./_components/Header/Header";
import { Toaster } from "@/components/ui/sonner"
import { Session } from "inspector/promises";
import { SessionProvider } from "next-auth/react";
import SessionProviderComp from "./_components/SessionProviderComp/SessionProviderComp";
import CartContextProvider from "./_context/CartContext";
import { getUserCart, getUserWishList } from "@/api/services/route.services";
import WishListContextProvider from "./_context/WishListContext";
 

const exo=Exo({
  variable:"--EXO--",
  subsets:["latin"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  const userCart= await getUserCart()
  const userWishList= await getUserWishList()
  
  return (
    <html
      lang="en"
      className={ ` ${exo.className} h-full antialiased` }
      
    >
      <body className={`${exo.className} min-h-full`}>


     <WishListContextProvider userWishList={userWishList}>

       <CartContextProvider userCart={userCart}>
          <SessionProviderComp>

           <Header/>
        <Navbar/>
        
        {children}
        <Toaster/>
        
        <Footer/>
        </SessionProviderComp>
       
      
      </CartContextProvider>
     </WishListContextProvider>
        </body>
    </html>
  );
}
